name: ğŸ³ Build & Deploy via Local Runner

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: ğŸ“¥ Cloner le dÃ©pÃ´t
      uses: actions/checkout@v4

    - name: ğŸ” Connexion sÃ©curisÃ©e Ã  Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ³ Build et Push de l'image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest

    - name: ğŸš€ DÃ©ploiement local
      run: |
        docker stop tpm-app-container || true
        docker rm tpm-app-container || true
        docker run -d --name tpm-app-container -p 8080:5000 docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
