name: ğŸ³ Build & Deploy via Local Runner

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: ğŸ“… Cloner le dÃ©pÃ´t
      uses: actions/checkout@v4

    - name: ğŸ” Connexion Ã  Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ·ï¸ Extraire les mÃ©tadonnÃ©es Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app

    - name: ğŸ³ Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: ğŸ›¡ï¸ GÃ©nÃ©rer une attestation dâ€™image
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: ğŸš€ DÃ©ploiement local
      run: |
        docker stop tpm-app-container || true
        docker rm tpm-app-container || true
        docker run -d --name tpm-app-container -p 8080:5000 docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
